### ISSUE TITLE
Error computed side-effects error when accessing getter

### ISSUE THREAD

**Issue by wittjosiah** [luisherranz/deepsignal#32]
When attempting to write a getter which consolidates a nested object, signals throws an error.

Reproduction:

```ts
const state = deepSignal({
  x: {
    a: 1,
    b: 2,
  },
  get y() {
    return Object.values((state.x as RevertDeepSignal<typeof state.x>) ?? {});
  },
});

console.log(state.y);
```

Error:
```
Error: Computed cannot have side-effects
      at mutationDetected (node_modules/.pnpm/@preact+signals-core@1.3.1/node_modules/@preact/signals-core/src/index.ts:5:8)
      at value (node_modules/.pnpm/@preact+signals-core@1.3.1/node_modules/@preact/signals-core/src/index.ts:314:4)
      at Object.values [as ownKeys] (node_modules/.pnpm/deepsignal@1.3.3_react@18.2.0/node_modules/deepsignal/core/src/index.ts:120:29)
      at Function.values (<anonymous>)
```

**Comment by luisherranz** [comment]
Interesting. It should be easy to fix. I just need to find another way to trick the minifier into thinking that the access to the `.value` shouldn't be removed in [this line](https://github.com/luisherranz/deepsignal/blob/main/packages/deepsignal/core/src/index.ts#L120).

Thanks for the report!

**Comment by luisherranz** [comment]
PR with the fix:

- https://github.com/luisherranz/deepsignal/pull/33

**Comment by wittjosiah** [comment]
Thanks for taking a look at this so quickly! I'll try it out once it's released.

**Comment by wittjosiah** [comment]
@luisherranz I'm getting back from some vacation earlier this week. Hoping I'll be able to try this out next week and I'll let you know if it resolves the issue I was seeing.

**Comment by wittjosiah** [comment]
@luisherranz I can confirm that I'm able to run the above code now without it crashing :+1: my apologies for the delay

**Comment by luisherranz** [comment]
Cool, thanks 🙂
